[package]
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
name = "check"
version = "0.1.0"

[dependencies]
afterparty = { git = "https://github.com/ms705/afterparty" }
error-chain = "0.11.0"
hyper = "0.10"
lazy_static = "0.2.9"
regex = "0.2.2"
reqwest = "0.8.1"