FROM debian:stretch
RUN apt update && apt install -y libssl1.1 ca-certificates && apt clean -y && apt autoclean -y && apt autoremove -y
COPY target/release/ci .
EXPOSE 4567
ENTRYPOINT ["./ci"]
CMD ["--help"]
